---
title: "sc_2021_joined"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


```{r Packages, message = FALSE}
library(scales)
library(tidyverse)
library(editData)

source("Functions/get_data_FITZROY_Function.R")
source("Functions/get_data_SQL_Function.R")
source("Functions/games_played_Function.R")
```



```{r Get data from fitzRoy and games played , message = FALSE}


# get past 10 years data from fitzroy and clean 
sql_data <- GetDataCleanMySQL()

# Get data from 2002 to be able to calculate games_played
afl_data <- GetDataCleanFitzRoy()

# Calculate games played using GamesPlayed function
afl_data2 <- GamesPlayed(afl_data)

# select only relevant variables
afl_data2 <- afl_data2 %>% select(c(id, helper, games_played)) %>% group_by(id, helper) %>% summarise(games_played = max(games_played)) 

merged_main_data <- merge(sql_data, afl_data2, by = "helper")


# remove unneeded variables and change team names to abbreivations to fit with pricing dataframe
main_data <- merged_main_data %>%
  select(c(ID, helper, first_name, surname, games_played, season, round, team, date, dfs_score, disposals)) %>%
  mutate(helper2 = paste0(first_name," ",surname,team))


```

```{r Get position and price data from excel, message = FALSE}

# get prices and postion data for 2021
prices_position_2021 <- read_csv("Data/2021_prices_positions.csv")

# create helper column to be able to merge
price_data <- prices_position_2021 %>%
  mutate(helper2 = paste0(Name, Team))
```


```{r DFS AVERAGE}

dfs_avg <-
  main_data %>%
  filter(season == 2020) %>%
  group_by(ID) %>%
  summarise(dfs_avg = mean(dfs_score)) %>%
  unique()
```

```{r TALENT}
# Talent = career high season average


talent <- 
  main_data %>%
  group_by(ID, season, helper2) %>%
  summarise(season_avg = mean(dfs_score)) %>%
  mutate(season_avg    = case_when(season == 2010 ~ (season_avg - 30),
                                   season == 2011 ~ (season_avg - 27),
                                   season == 2012 ~ (season_avg - 24),
                                   season == 2013 ~ (season_avg - 21),
                                   season == 2014 ~ (season_avg - 18),
                                   season == 2015 ~ (season_avg - 15),
                                   season == 2016 ~ (season_avg - 12),
                                   season == 2017 ~ (season_avg - 9),
                                   season == 2018 ~ (season_avg - 6),
                                   season == 2019 ~ (season_avg - 3),
                                   season == 2020 ~ (season_avg - 1))) %>%
  group_by(ID, helper2) %>%
  summarise(talent = round(max(season_avg), 2)) %>%
  ungroup() %>%
  unique()
  


```

```{r OPPURTUNITY USAGE}
# Opportunity = disposals / team disposals


opportunity <- 
  main_data %>%
  filter(season == 2020) %>%
  group_by(ID) %>%
  summarise(disposal_mean = mean(disposals)) %>%
  # ungroup() %>%
  merge(main_data) %>%
  filter(season == 2020) %>%
  group_by(ID,helper2) %>%
  summarise(opportunity = case_when(team == "FRE" ~ round((disposal_mean/299.9)*100,2),
                                    team == "ADE" ~ round((disposal_mean/282.5)*100,2),
                                    team == "CAR" ~ round((disposal_mean/281.2)*100,2),
                                    team == "ESS" ~ round((disposal_mean/302.4)*100,2),
                                    team == "GEE" ~ round((disposal_mean/310.4)*100,2),
                                    team == "HAW" ~ round((disposal_mean/314.9)*100,2),
                                    team == "WCE" ~ round((disposal_mean/286.3)*100,2),
                                    team == "NME" ~ round((disposal_mean/300.1)*100,2),
                                    team == "POR" ~ round((disposal_mean/308.7)*100,2),
                                    team == "GCS" ~ round((disposal_mean/285.4)*100,2),
                                    team == "SYD" ~ round((disposal_mean/292.8)*100,2),
                                    team == "COL" ~ round((disposal_mean/314.9)*100,2),
                                    team == "STK" ~ round((disposal_mean/292.4)*100,2),
                                    team == "WBD" ~ round((disposal_mean/309.9)*100,2),
                                    team == "RIC" ~ round((disposal_mean/290.2)*100,2),
                                    team == "MEL" ~ round((disposal_mean/296.5)*100,2),
                                    team == "BRI" ~ round((disposal_mean/279.5)*100,2),
                                    team == "GWS" ~ round((disposal_mean/298.5)*100,2))) %>%
  ungroup() %>%
  unique()

```

```{r DURABILITY LEVEL}
# Durability Level = % of games played last two years



# 2020 games max = 17

durability <-
  main_data %>%
  filter(season >2019 & date < "2020-09-22") %>%
  mutate(played_game = 1) %>%
  group_by(ID, helper2) %>%
  arrange(date) %>%
  mutate(games_played = cumsum(played_game),
         durability = round((games_played/17)*100, 2)) %>%
  group_by(ID) %>%
  dplyr::filter(date == max(date)) %>%
  ungroup() %>%
  select(c(ID, durability))
  
  

```

```{r FORM}
# Form = 2nd half of the season average 

# 2nd of August is the mid point of the 2020 season

form <-
  main_data %>%
  dplyr::filter(date > "2020-08-03") %>%
  mutate(played_game = 1) %>%
  group_by(ID) %>%
  arrange(date) %>%
  mutate(games_played = cumsum(played_game)) %>%
  filter(games_played > 3) %>%
  summarise(form = round(mean(dfs_score), 2)) %>%
  select(c(ID, form))




```

```{r CONSISTENCY}
consistency <-
  main_data %>%
  dplyr::filter(season == 2020) %>%
  mutate(played_game = 1,
         above_100   = ifelse(dfs_score > 80, 1, 0)) %>%
  group_by(ID) %>%
  arrange(date) %>%
  mutate(games_played  = sum(played_game),
         above_100_sum = sum(above_100)) %>%
  filter(games_played > 3) %>%
  summarise(consistency = round(above_100_sum/games_played, 2)) %>%
  select(c(ID, consistency)) %>%
  unique()

```


```{r Combine all FACTORS}

all_factors <- left_join(talent, opportunity)
all_factors <- left_join(all_factors, durability)
all_factors <- left_join(all_factors, form)
all_factors <- left_join(all_factors, consistency)
all_factors <- left_join(all_factors, dfs_avg)

final <- all_factors %>%
  unique() %>%
  group_by(ID) %>%
  select(c(ID, name = helper2, talent, opportunity, durability, form, consistency, dfs_avg)) 

```


```{r JOIN prices data and supercoach data}

# upate helper names and team in final dataset
final_updated <- final %>%
  mutate(helper2 = case_when(name == "Adam SaadESS" ~ "Adam SaadCAR",
                             name == "Adam TreloarCOL" ~ "Adam TreloarWBD",
                             name == "Aidan CorrGWS" ~ "Aidan CorrNME",
                             name == "Alex WitherdenBRI" ~ "Alex WitherdenWCE",
                             name == "Aliir AliirSYD" ~ "Aliir AliirPOR",
                             name == "Ben BrownNME" ~ "Ben BrownMEL",
                             name == "Brad CloseGEE" ~ "Bradley CloseGEE",
                             name == "Brad CrouchADE" ~ "Brad CrouchSTK",
                             name == "Braydon PreussMEL" ~ "Braydon PreussGWS",
                             name == "Cam RaynerBRI" ~ "Cameron RaynerBRI",
                             name == "Conor McKennaESS" ~ "Conor MckennaESS",
                             name == "Colin ORiordanSYD" ~ "Colin O'RiordanSYD",
                             name == "Fischer McAseyADE" ~ "Fischer McaseyADE",
                             name == "Isaac SmithHAW" ~ "Isaac SmithGEE",
                             name == "Jack HigginsRIC" ~ "Jack HigginsSTK",
                             name == "Jackson HatelyGWS" ~ "Jackson HatelyADE",
                             name == "Jacob TownsendESS" ~ "Jacob TownsendGCS",
                             name == "Jaeger OMearaHAW" ~ "Jaeger O'MearaHAW",
                             name == "Jaidyn StephensonCOL" ~ "Jaidyn StephensonNME",
                             name == "James FrawleyHAW" ~ "James FrawleySTK",
                             name == "Jeremy CameronGWS" ~ "Jeremy CameronGEE",
                             name == "Joe DaniherESS" ~ "Joe DaniherBRI",
                             name == "Jordan de GoeyCOL" ~ "Jordan De GoeyCOL",
                             name == "Josh KennedySYD" ~ "Josh P. KennedySYD",
                             name == "Jye CaldwellGWS" ~ "Jye CaldwellESS",
                             name == "Lachie FogartyGEE" ~ "Lachie FogartyCAR",
                             name == "Lachie YoungWBD" ~ "Lachie YoungNME",
                             name == "Lochie OBrienCAR" ~ "Lochie O'BrienCAR",
                             name == "Majak DawNME" ~ "Majak DawPOR",
                             name == "Mark OConnorGEE" ~ "Mark O'ConnorGEE",
                             name == "Mason WoodNME" ~ "Mason WoodSTK",
                             name == "Mitch HannanMEL" ~ "Mitch HannanWBD",
                             name == "Oleg MarkovRIC" ~ "Oleg MarkovGCS",
                             name == "Orazio FantasiaESS" ~ "Orazio FantasiaPOR",
                             name == "Reilly OBrienADE" ~ "Reilly O'BrienADE",
                             name == "Shaun HigginsNME" ~ "Shaun HigginsGEE",
                             name == "Shaun McKernanESS" ~ "Shaun McKernanSTK",
                             name == "Stefan MartinBRI" ~ "Stefan MartinWBD",
                             name == "Tim OBrienHAW" ~ "Tim O'BrienHAW",
                             name == "Tom PhillipsCOL" ~ "Tom PhillipsHAW",
                             name == "Zac WilliamsGWS" ~ "Zac WilliamsCAR", TRUE ~ name)) %>%
  select(helper2, everything())


# ---------------------------------------------------------------------------------------------------------------------#
  
# WEIGHTINGS

talent_weight      = 20
opportunity_weight = 13
durability_weight  = 8
consistency_weight = 5
form_weight        = 8

# ---------------------------------------------------------------------------------------------------------------------#

# combine price and supercoach data

joined_data <- left_join(price_data, final_updated, by = "helper2")


# Fix any factors that are 0's or NA
fixed_data <- joined_data %>% 
  mutate(talent      = case_when(is.na(talent)      ~ `2020_Average`,    TRUE ~ talent),
         opportunity = case_when(is.na(opportunity) ~ 0,                 TRUE ~ opportunity),
         durability  = case_when(is.na(durability)  ~ (`2020_Games`/17), TRUE ~ durability),
         form        = case_when(is.na(form)        ~ `2020_Average`,    TRUE ~ form),
         consistency = case_when(is.na(consistency) ~ 0,                 TRUE ~ consistency),
         manual_weight = 0) %>%
  select(-c(ID, name, dollar_Per_Point)) %>%
  select(helper2, everything())



```


```{r RESCALE and PREDICT}

# RESCALE VARIABLES
complete_data <- fixed_data %>%
  mutate(opportunity = case_when(Position == "RUC" ~ (1.75 * opportunity), TRUE ~ opportunity)) %>%
  mutate(weighted_talent      = round(rescale(talent,      to = c(0.01, talent_weight)), 2)) %>%
  mutate(weighted_opportunity = round(rescale(opportunity, to = c(0.01, opportunity_weight)), 2)) %>%
  mutate(weighted_durability  = round(rescale(durability,  to = c(0.01, durability_weight)), 2)) %>%
  mutate(weighted_form        = round(rescale(form,        to = c(0.01, form_weight)), 2)) %>%
  mutate(weighted_consistency = round(rescale(consistency, to = c(0.01, consistency_weight)), 2)) %>%
  mutate(rating = (weighted_talent + weighted_opportunity + weighted_durability + weighted_form + weighted_consistency))

```


```{r PROJECTIONS}

# Finds difference factor which is used to multiple model_raw results to get a realistic projection

# remove players who averaged below 30

model_dataset   <- complete_data %>% filter(dfs_avg > 30) 
median_dfs      <- median(model_dataset$dfs_avg)
median_model    <- median(model_dataset$rating)
diff_factor     <- median_dfs / median_model                        # used 59 as it was the average between median and visual


# model projected scores

projections <- 
  model_dataset %>% mutate(projected = (rating * diff_factor) * 0.95)


# ADP
```


```{r GET REPLACMENT LEVEL VALUES}
# get replacment level values for each position
def_replacment <- projections %>% filter(Position == "DEF") %>% arrange(desc(projected)) %>% slice(50) %>% select(replace_value = projected)
mid_replacment <- projections %>% filter(Position == "MID") %>% arrange(desc(projected)) %>% slice(70) %>% select(replace_value = projected)
ruc_replacment <- projections %>% filter(Position == "RUC") %>% arrange(desc(projected)) %>% slice(10) %>% select(replace_value = projected)
fwd_replacment <- projections %>% filter(Position == "FWD") %>% arrange(desc(projected)) %>% slice(50) %>% select(replace_value = projected)

# combine back together
adp_dataset <- rbind(def_replacment, mid_replacment, ruc_replacment, fwd_replacment)
# Calculate ADP
adp_dataset <- projections %>% mutate(replace_value = case_when(Position == "DEF" ~ def_replacment$replace_value,
                                                                Position == "MID" ~ mid_replacment$replace_value,
                                                                Position == "RUC" ~ ruc_replacment$replace_value,
                                                                Position == "FWD" ~ fwd_replacment$replace_value)) %>%
  select(c(Name, Team, Position, Proj = projected, replace_value))
```


```{r SAVE AS CSV}
write.csv(adp_dataset, "dfs_adp.csv")
```









