---
title: "dt_keeper_adp_model"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load Packages, warning=FALSE}
library(dplyr)
library(elo)
library(lubridate)
library(fitzRoy)
library(tidyr)
library(ggplot2)
library(readr)
```

```{r Import data}
# fitzRoy inport
stats <- get_afltables_stats(start_date = "2018-01-01", end_date = "2020-12-01")


# 2020 fitzRoy import
stats_2020 <- get_afltables_stats(start_date = "2020-01-01", end_date = "2020-12-01")


# player position ID imporat
players_position <- read_csv("player_id.csv")


# ultiate footy positions
uf_positions <- read_csv("uf_positions.csv")


```

```{r Manipulate}

# select only relevant variables from postions dataframes
players_position <-
  players_position %>% select(FirstLastTeam, DvP_position = `DvP Position`, Position)

uf_positions <-
  uf_positions %>% select(FirstLastTeam, uf_position = POS)

# Make round column numeric (removes finals)
stats_manip <- stats %>% mutate(Round = as.numeric(Round))

# add abb team name to fitzRoy df 
stats_manip<- 
  stats %>%
  mutate(team_abb = case_when(Playing.for == "Carlton"                ~ "CAR",
                              Playing.for == "Collingwood"            ~ "COL",
                              Playing.for == "St Kilda"               ~ "STK",
                              Playing.for == "Sydney"                 ~ "SYD",
                              Playing.for == "Essendon"               ~ "ESS",
                              Playing.for == "Gold Coast"             ~ "GCS",
                              Playing.for == "North Melbourne"        ~ "NME",
                              Playing.for == "Adelaide"               ~ "ADE",
                              Playing.for == "Fremantle"              ~ "FRE",
                              Playing.for == "Richmond"               ~ "RIC",
                              Playing.for == "Western Bulldogs"       ~ "WBD",
                              Playing.for == "Hawthorn"               ~ "HAW",
                              Playing.for == "Greater Western Sydney" ~ "GWS",
                              Playing.for == "Brisbane Lions"         ~ "BRI",
                              Playing.for == "West Coast"             ~ "WCE",
                              Playing.for == "Geelong"                ~ "GEE",
                              Playing.for == "Melbourne"              ~ "MEL",
                              Playing.for == "Port Adelaide"          ~ "POR"),
         first_initial = c(substr(First.name, 0, 1)),                          # get first initial
         last_name     = Surname,                                              # extract last name
         FirstLastTeam = paste0(first_initial, last_name, team_abb)) %>%
         left_join(players_position, by = "FirstLastTeam")

# add Ultimate Footy positions
stats_manip <- stats_manip %>% left_join(uf_positions, by = "FirstLastTeam")        # add Ultimate Footy positions

```

```{r Keys}
# DT scoring system
dfs_kick <- 3
dfs_mark <- 3
dfs_hb <- 2
dfs_ho <- 1
dfs_fa <- -3 
dfs_ff <- 1
dfs_goal <- 6
dfs_behind <- 1
dfs_tackle <- 4

# Team Disposals
team_disp <- tibble(team      = c("Carlton", "Collingwood", "St Kilda", "Sydney", "Essendon", "Gold Coast", "North Melbourne", "Adelaide", "Fremantle", "Richmond", "Western Bulldogs", "Hawthorn",                                          "Greater Western Sydney", "Brisbane Lions", "West Coast", "Geelong", "Melbourne",
                                  "Port Adelaide"), 
                    team_disp = c(347, 399.2, 388.7, 371.7, 381.6, 339.9, 367.9, 383, 363.1, 366.8, 387.6, 376.5, 377.9,                                    373.5, 356.1, 380.1, 386.2, 375.5))
```

```{r Create new variables: Risk, Form, Talent, Usage}

# Make round column numeric (removes finals)
stats_manip <- stats_manip %>% mutate(Round = as.numeric(Round))

# create player id
stats_manip <- stats_manip %>% mutate(player_id = paste(First.name, Surname, ID, sep = ""))


# add DT scores
stats_manip <- 
  stats_manip %>%
  mutate(k_dfs = Kicks * dfs_kick,
         hb_dfs = Handballs * dfs_hb,
         mark_dfs = Marks * dfs_mark,
         tackle_dfs = Tackles * dfs_tackle,
         ho_dfs = Hit.Outs * dfs_ho,
         fa_dfs = Frees.Against * dfs_fa,
         ff_dfs = Frees.For * dfs_ff,
         goal_dfs = Goals * dfs_goal,
         behind_dfs = Behinds * dfs_behind) %>%
  mutate(dfs_score = k_dfs + hb_dfs + mark_dfs + tackle_dfs + ho_dfs + fa_dfs + ff_dfs + goal_dfs + behind_dfs)


# create player season averages and RISK
averages <- 
  stats_manip %>%
  filter(Season == 2019 & Round < 24) %>%
  group_by(player_id, FirstLastTeam, Playing.for, DvP_position, Position, uf_position) %>%
  summarise(games_played = n(),
            dt_avg       = round(mean(dfs_score)),
            disp_avg     = round(mean(Kicks + Handballs))) %>%
  mutate(risk            = round((games_played / 22) * 100))


# create form (last 12 avg)
form <- 
  stats_manip %>%
  filter(Season == 2019 & Round >= 12 & Round < 24) %>%
  group_by(player_id) %>%
  summarise(form     = mean(dfs_score)) 
    


# create talent (highest previous 3 year average)
talent <- 
  stats_manip %>%
  filter(Round <24) %>%
  group_by(player_id, Season) %>%
  summarise(highest_avg   = mean(dfs_score)) %>%
  group_by(player_id) %>%
  mutate(talent          = max(highest_avg)) %>%
  filter(Season == 2019)
 

# create team_role (% of disp of team disposals - using as a proxy for role in team)
combined <- left_join(averages, team_disp, by = c("Playing.for" = "team" ))

# create USAGE
combined <- 
  combined %>%
  mutate(usage = (disp_avg / team_disp) * 100)


# add form and talent to averages tibble
combined <- 
  merge(combined, talent, by = "player_id", all = TRUE) 

combined <- 
  merge(combined, form, by = "player_id", all = TRUE)


# remove unnessacary variables and convert NA's in form to dt_avg
combined <- 
  combined %>%
  mutate(form   = replace(form, is.na(form), dt_avg),
         talent = (talent + dt_avg) / 2) 
```

```{r Send to excel and manually chancge UF positions}
write.csv(combined, "combined_write.csv")
  
combined_read <- read.csv("combined_read.csv")

combined_read <- combined_read %>% drop_na(uf_position)
```

```{r Add 2020 R1 weighting update}

# create dt_score and playerID variables
stats_2020 <- 
  stats_2020 %>%
  mutate(player_id = paste(First.name, Surname, ID, sep = "")) %>%
  mutate(k_dfs = Kicks * dfs_kick,
         hb_dfs = Handballs * dfs_hb,
         mark_dfs = Marks * dfs_mark,
         tackle_dfs = Tackles * dfs_tackle,
         ho_dfs = Hit.Outs * dfs_ho,
         fa_dfs = Frees.Against * dfs_fa,
         ff_dfs = Frees.For * dfs_ff,
         goal_dfs = Goals * dfs_goal,
         behind_dfs = Behinds * dfs_behind) %>%
  mutate(dfs_score = k_dfs + hb_dfs + mark_dfs + tackle_dfs + ho_dfs + fa_dfs + ff_dfs + goal_dfs + behind_dfs) %>%
  select(player_id, dfs_score)

# join 2020 stats to combined_read and change NA's to be orignal dt_avg
combined_read <- combined_read %>% left_join(stats_2020, by ="player_id") 

combined_read <- combined_read %>% mutate(r1_score = ifelse(is.na(dfs_score), dt_avg, dfs_score))
```

```{r Create Player Ranking Model}

# Weighting keys
talent_weight <- 30
risk_weight   <- 5
form_weight   <- 20
usage_weight  <- 15
weight_2020   <- 3

# Standardize and weight each variable

model_calc <- 
  combined_read %>%
  mutate(talent_calc      = (talent - min(talent)) / (max(talent) - min(talent)) * talent_weight,
         risk_calc        = (risk - min(risk)) / (max(risk) - min(risk)) * risk_weight,
         form_calc        = (form - min(form)) / (max(form) - min(form)) * form_weight,
         usage_calc       = (usage - min(usage)) / (max(usage) - min(usage)) * usage_weight, 
         usage_calc       = ifelse(uf_position == "RUC", usage_calc * 1.5, usage_calc),
         weight_2020_calc = (r1_score - min(r1_score)) / (max(r1_score) - min(r1_score)) * weight_2020,
         model_raw        = talent_calc + risk_calc + form_calc + usage_calc + weight_2020_calc)
```

```{r Create final model and ADP}

# Finds difference factor which is used to multiple model_raw results to get a realistic projection

# remove players who averaged below 30

model_dataset   <- model_calc %>% filter(dt_avg > 30) 
median_dfs      <- median(model_dataset$dt_avg)
median_model    <- median(model_dataset$model_raw)
diff_factor     <- median_dfs / mean_model                        # used 59 as it was the average between median and visual


# model projected scores

projections <- 
  model_dataset %>%
  mutate(projected = (model_raw * diff_factor) * 0.95) %>%
  select(-c(1,3,5,6,8,12,14,15,18,20,21,22,23,24))


# use combined_read to find replacment values based on below numbre of players per position


# 6 - def
# 8 - mid
# 2 - ruc
# 6 - fwd

ruc_replacment_level <- 73
fwd_replacment_level <- 69
def_replacment_level <- 70
mid_replacment_level <- 80



# create ADP (adjusted draft position)
adp_final <- 
  projections %>%
  mutate(adp = as.numeric(ifelse(uf_position == "RUC", projected - ruc_replacment_level,
                          ifelse(uf_position == "FWD", projected - fwd_replacment_level,
                          ifelse(uf_position == "DEF", projected - def_replacment_level,
                          ifelse(uf_position == "MID", projected - mid_replacment_level, ""))))))


# add positional ranking
adp_final <- 
  adp_final %>%
  group_by(uf_position) %>%
  mutate(position_rank = dense_rank(desc(projected)))
```

```{r Export to csv}
write_csv(adp_final, "adp_final.csv")
```





