---
title: "Supercoach_Optimiser_2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r LOAD packages}

library(tidyverse)
library(lpSolve)
```

```{r READ data}

supercoach_proj <- read_csv("projections_2021.csv")
```


```{r Optimiser}

dataset <- supercoach_proj %>% na.omit()

name <- dataset$Name
pos  <- dataset$Position
pts  <- dataset$proj_score
cost <- dataset$Price


f <- pts


maxPts <- 10000
lineup_no <- 10




lineups <- vector("list", length(lineup_no))
for(i in 1:lineup_no)
{

  
####################
#Constraints
###################

# Prepare constraint matrix of zeros
A <- matrix(0, nrow = 6, ncol = nrow(dataset))       # row = 5, columns = number of rows in orginal dataset


#Designate the positions that are equivalent to each other when generating the optimal lineup
#There are 4 distinct positions and 1 constraint in which salary is < 50,000
#I.e. A player with the position M/F can fill the M or the F position
#Add a "1" to all position that can fill that position slot


#Set F parameters
j<-1
k<-1
for (k in 1:nrow(dataset)){
  if (dataset$Position[k] == "FWD")
    A[j,k]<-1
}

#Set M parameters
j<-2
k<-1
for (k in 1:nrow(dataset)){
  if (dataset$Position[k] == "MID")
    A[j,k]<-1
}


#Set D parameters
j<-3
k<-1
for (k in 1:nrow(dataset)){
  if (dataset$Position[k] == "DEF")
    A[j,k]<-1
}


#Set R parameters
j<-4
k<-1
for (k in 1:nrow(dataset)){
  if (dataset$Position[k] == "RUC")
    A[j,k]<-1
}




A[5, ] <- dataset$Price               # salary <= 50000
A[6, ] <- f

# Prepare input for LP solver
dfs_objective        <- f
const_matrix         <- A
const_direction      <- c("==",
                          "==",
                          "==",
                          "==",
                          "<=",
                          "<=")
const_righthand_side <- c(6,
                          8,
                          6,
                          2,
                          10000000,
                          maxPts)


##################################
#Run optimal lineup with lpSolve
##################################

# Generate optimal lineup with lp solve

solve <- lp(direction = "max", dfs_objective, # maximize objective function
            const_matrix,
            const_direction,
            const_righthand_side,   # constraints
            all.bin = TRUE)         # use binary variables only

### View the solution
score      <- sum(pts[solve$solution > 0])                # gets predicted score (by summing all solution that = 1)
indicators <- which(solve$solution == 1)                            # filter only solution == 1 (filters optimal lineup)
salary     <- sum(dataset$Price[indicators])                       # gets salary spent                                         
lineup <- dataset[indicators, ]                                   # Create dataset with optimal lineup 


  lineup <- lineup %>% arrange(match(Position, c("FWD", "RUC", "MID", "DEF")), desc(Price)) # order lineup by position
  lineupNumber <- i
  print(lineupNumber)
  print(score)
  print(salary)
  
  print(lineup)
  
  lineups[[i]] <- lineup
  maxPts <- score - 0.0001
  
  
  

  final_df <- as.data.frame(lineup)
                      

  }
```

